version: '3'
services:
  mongodb:
    image: mongo:latest  
    container_name: reddit_posts_storage
    environment:
      - MONGO_INITDB_ROOT_USERNAME=crawler  
      - MONGO_INITDB_ROOT_PASSWORD=crawler
    ports:
      - "27017:27017" 
    volumes:
      - /home/backup:/data/db  