version: '3'
services:
  crawler_eusouobabaca:
    image: reddit_crawler
    container_name: reddit_crawler_create_posts_Eu_Sou_OBabaca
    environment:
      - forum=EuSouOBabaca
      - interval=20
      - mode=crawler
    depends_on:
      - mongodb
  crawler_brdev:
    image: reddit_crawler
    container_name: reddit_crawler_create_posts_brdev
    environment:
      - forum=brdev
      - interval=12
      - mode=crawler
    depends_on:
      - mongodb
  update_brdev:
    image: reddit_crawler
    container_name: reddit_crawler_update_posts_brdev
    environment:
      - forum=brdev
      - interval=15
      - mode=update
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest  
    container_name: reddit_posts_storage
    environment:
      - MONGO_INITDB_ROOT_USERNAME=crawler  
      - MONGO_INITDB_ROOT_PASSWORD=crawler
    ports:
      - "27017:27017" 
    volumes:
      - /home/backup:/data/db  